[[agents]]
file = "documentador.toml"
category = "Documentação"
maintainer = "A definir"

[[agents]]
file = "ola-teste.toml"
category = "teste"
maintainer = "Samuel Vieira"

[[agents]]
file = "pato-bobo.toml"
category = "teste"
maintainer = "Samuel"

[[agents]]
file = "planejador-testes.toml"
category = "Qualidade"
maintainer = "A definir"

[[agents]]
file = "revisor-codigo.toml"
category = "Desenvolvimento"
maintainer = "A definir"

[[agents]]
file = "teste-local.toml"
category = "testes"
maintainer = "Samuel Vieira"
