[[agents]]
file = "calculadora-basica.toml"
category = "teste"
maintainer = "Samuel Vieira"

[[agents]]
file = "controle-volume.toml"
category = "teste"
maintainer = "Samuel Vieira"

[[agents]]
file = "designer-cli.toml"
category = "designer"
maintainer = "Samuel Vieira"

[[agents]]
file = "diagnosta-agentscloud.toml"
category = "diagnostico"
maintainer = "Samuel Vieira"

[[agents]]
file = "documentador.toml"
category = "Documentação"
maintainer = "Samuel Vieira"

[[agents]]
file = "piadista-ia.toml"
category = "teste"
maintainer = "Samuel Vieira"

[[agents]]
file = "revisor-codigo.toml"
category = "revisor"
maintainer = "Samuel Vieira"

[[agents]]
file = "teste-local.toml"
category = "Documentação"
maintainer = "Samuel Vieira"

[[agents]]
file = "teste-remoto.toml"
category = "teste"
maintainer = "Samuel Vieira"
